### ISSUE TITLE
Error count() in class.attachments.search.php:64

### ISSUE THREAD

**Issue by didwedo** [jchristopher/attachments#193]
When I erase an image in backend, it disappears. then by reloading the media page, it is still there, if I click on detail, I have a gray icon default, by deleting it again I have the following big error: 

[22-Mar-2022 14:25:24 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.search.php:64
Stack trace:
#0 /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.php(301): AttachmentsSearch->__construct(NULL, Array)
#1 /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.php(211): Attachments->search(NULL, Array)
#2 /home/httpd/vhosts/abc.com/wp-includes/class-wp-hook.php(309): Attachments->handle_wp_post_delete(402906)
#3 /home/httpd/vhosts/abc.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#4 /home/httpd/vhosts/abc.com/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /home/httpd/vhosts/abc.com/wp-includes/post.php(6413): do_action('delete_post', 402906, Object(WP_Post))
#6 /home/httpd/vhosts/abc.com/wp-includes/post.php(3381): wp_delete_attachment(402906, false)
#7 /home/httpd/vhosts/abc.com/wp-admin/includes/ajax-actions.php(855): wp_delete_post(402906)
#8 /home/httpd/vhosts/abc.com/wp-includes/class-wp-hook.php(307): wp_ajax_delete_post('delete-post')
#9 /home/httpd/vhosts/abc.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#10 /home/httpd/vhosts/abc.com/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#11 /home/httpd/vhosts/abc.com/wp-admin/admin-ajax.php(187): do_action('wp_ajax_delete-...')
#12 {main}
  thrown in /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.search.php on line 64
[22-Mar-2022 14:25:27 UTC] PHP Deprecated:  wp_richedit_pre est <strong>obsolÃ¨te</strong> depuis la version 4.3.0Â ! Utilisez format_for_editor() Ã  la place. in /home/httpd/vhosts/abc.com/wp-includes/functions.php on line 5316
[22-Mar-2022 14:26:03 UTC] PHP Deprecated:  wp_richedit_pre est <strong>obsolÃ¨te</strong> depuis la version 4.3.0Â ! Utilisez format_for_editor() Ã  la place. in /home/httpd/vhosts/abc.com/wp-includes/functions.php on line 5316
[22-Mar-2022 14:26:07 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.search.php:64
Stack trace:
#0 /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.php(301): AttachmentsSearch->__construct(NULL, Array)
#1 /home/httpd/vhosts/abc.com/wp-content/plugins/attachments/classes/class.attachments.php(211): Attachments->search(NULL, Array)
#2 /home/httpd/vhosts/abc.com/wp-includes/class-wp-hook.php(309): Attachments->handle_wp_post_delete(402906)
#3 /home/httpd/vhosts/abc.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#4 /home/httpd/vhosts/abc.com/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /home/httpd/vhosts/abc.com/wp-includes/post.php(6413): do_action('delete_post', 402906, Object(WP_Post))
#6 /home/httpd/vhosts/abc.com/wp-admin/post.php(321): wp_delete_attachment(402906, true)
#7 {main}
  thrown i

**Comment by abmcr** [comment]
I have solved with this fix
line 64-66
if(is_countable($params['fields'])):for ( $i = 0; $i < count( $params['fields'] ); $i++ ) {
            $params['fields'][ $i ] = sanitize_text_field( $params['fields'][ $i ] );
}endif;

**Comment by didwedo** [comment]
Hello,

Thank you very much, your plugin are so incredible.

Have a good time

Best regards
Chris



 <https://www.didwedo.ch/>
Rue de Sébeillon 9b
CH-1004 Lausanne
+41 21 625 22 35
www.didwedo.ch <https://www.didwedo.ch/>

**Comment by angryaxi** [comment]
There is a pull request fixing this issue: #194 
If someone with merge permissions could take a look at it, this issue could be solved and closed.
